language: go
go:
  - "1.11.1"

services:
  - docker

env:
  - GO111MODULE=on

install: true

stages:
  - "Tests"
  - name: "Deploy"
    if: tag IS present

jobs:
  include:
    - stage: "Tests"
      name: "Unit Tests"
      script: make test
    - stage: "Deploy"
      name: "Build and deploy reception"
      script:
        - docker build -f ./Dockerfile_reception -t italolelis/reception:$TRAVIS_TAG .
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        - docker push italolelis/reception:$TRAVIS_TAG
        - docker push italolelis/reception
    - name: "Build and deploy barista"
      script:
        - docker build -f ./Dockerfile_barista -t italolelis/barista:$TRAVIS_TAG .
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        - docker push italolelis/barista:$TRAVIS_TAG
        - docker push italolelis/barista

