language: go
go:
  - "1.11.1"

services:
  - docker

env:
  - GO111MODULE=on

install: true

jobs:
  include:
    - stage: "Tests"
      name: "Unit Tests"
      script: make test
    - stage: "Build and Deploy"
      if: tag IS present
      name: "Build and deploy reception"
      script:
        - docker build -f ./Dockerfile_reception -t italolelis/reception:$TRAVIS_COMMIT .
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        - docker push italolelis/reception:$TRAVIS_COMMIT
    - name: "Build and deploy barista"
      script:
        - docker build -f ./Dockerfile_barista -t italolelis/barista:$TRAVIS_COMMIT .
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        - docker push italolelis/barista:$TRAVIS_COMMIT
